# source: https://medium.com/@its-andrerebonato/setting-up-a-basic-ci-cd-pipeline-for-deploying-a-node-js-application-on-digitalocean-8797aa2c8049

name: CI/CD - Deploy myapp backend [dev]

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

      # symlinks gets affected without the -y opt for zip
      # useful for sequelize-cli
      - name: Zip artifact for deployment
        run: |
          mkdir node-app && mv ./contrib/pm2.config.cjs package* .sequelizerc ./app ./node_modules node-app 
          zip node-app.zip node-app -ryq

      - name: Upload built zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip
          retention-days: 1

      - uses: actions/download-artifact@v4
        with:
          name: node-app
          path: distfiles

      - name: Copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_SSH_HOST }}
          username: ${{ secrets.VM_SSH_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT }}
          source: distfiles/*
          target: /opt/myapp/backend

      - name: SSH and clean up the dist
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_SSH_HOST }}
          username: ${{ secrets.VM_SSH_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT }}
          script: |
            cd /opt/myapp/backend
            if [ -d node_modules ]
            then
              echo "Stopping backend service and removing old build"
              npx pm2 stop pm2.config.cjs
              rm -rf node_modules pm2.config.cjs
            fi
            cd distfiles
            unzip node-app.zip
            mv node-app/{.*,*} ../
            cd ..
            rm -rf distfiles
            npx pm2 restart pm2.config.cjs
            echo "All done"
