# source: https://medium.com/@its-andrerebonato/setting-up-a-basic-ci-cd-pipeline-for-deploying-a-node-js-application-on-digitalocean-8797aa2c8049

name: CI/CD - Deploy myapp backend [dev]

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip node-app.zip ./contrib/pm2.config.js ./app ./node_modules -r

      - name: Upload built zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip
          retention-days: 1

      - uses: actions/download-artifact@v4
        with:
          name: node-app
          path: distfiles

      - name: Copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_SSH_HOST }}
          username: ${{ secrets.VM_SSH_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT }}
          source: distfiles/*
          target: /opt/myapp/backend

      - name: SSH and clean up the dist
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_SSH_HOST }}
          username: ${{ secrets.VM_SSH_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_SSH_PORT }}
          script: |
            cd /opt/myapp/backend
            echo "Stopping backend service and removing old build"
            npx pm2 stop pm2.config.js
            rm -rf dist node_modules pm2.config.js
            cd distfiles
            unzip node-app.zip
            mv dist ../
            cd ..
            mv distfiles/contrib/pm2.config.js .
            mv distfiles/node_modules .
            rm -rf distfiles
            npx pm2 restart pm2.config.js
            echo "All done"
